---
sudo: false
language: python

# LOL!
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34-django20-wagtail20

    - python: 3.5
      env: TOXENV=py34-django20-wagtail20

    - python: 3.6
      env: TOXENV=py36-django20-wagtail20

  allow_failures:
    - python: 3.5
      env: TOXENV=lint


install:
  - pip install tox codecov


script:
  - tox


after_success:
  - tox -e coverage-report
  - codecov
